[book]
title = "How do you Tauri"
authors = []
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
default-theme = "dark"
preferred-dark-theme = "ayu"
additional-js = ["theme/enable-checkboxes.js"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.epub]
optional = true
#additional-css = ["./path/to/main.css"]
#use-default-css = false
#cover-image = "ebook-cover.png"
#additional-resources = ["./assets/Open-Sans-Regular.ttf"]
#no-section-label = true
#curly-quotes = true
